// packages/solid/src/Chart.tsx
import { createEffect, createSignal, onCleanup, onMount } from 'solid-js'
import type { JSX } from 'solid-js'
import type { Chart as ChartCore, ChartConfig, ChartData } from '@ldesign/chart-core'
import { createChart } from '@ldesign/chart-core'

export interface ChartProps {
  type: ChartConfig['type']
  data: ChartData
  title?: string
  theme?: string
  darkMode?: boolean
  responsive?: boolean
  config?: Partial<ChartConfig>
  onInit?: (chart: ChartCore) => void
  onClick?: (params: any) => void
}

export function Chart(props: ChartProps): JSX.Element {
  const [container, setContainer] = createSignal<HTMLElement>()
  const [chart, setChart] = createSignal<ChartCore>()

  onMount(() => {
    const el = container()
    if (!el) return

    const chartConfig: ChartConfig = {
      type: props.type,
      data: props.data,
      title: props.title,
      theme: props.theme,
      darkMode: props.darkMode,
      responsive: props.responsive,
      ...props.config,
    }

    const chartInstance = createChart(el, chartConfig)

    chartInstance.on('click', (params: any) => {
      props.onClick?.(params)
    })

    setChart(chartInstance)
    props.onInit?.(chartInstance)
  })

  createEffect(() => {
    const chartInstance = chart()
    if (chartInstance) {
      chartInstance.updateData(props.data)
    }
  })

  createEffect(() => {
    const chartInstance = chart()
    if (chartInstance && props.theme) {
      chartInstance.setTheme(props.theme)
    }
  })

  createEffect(() => {
    const chartInstance = chart()
    if (chartInstance && props.darkMode !== undefined) {
      chartInstance.setDarkMode(props.darkMode)
    }
  })

  onCleanup(() => {
    chart()?.dispose()
  })

  return <div ref={setContainer} style={{ width: '100%', height: '100%' }} />
}

export default Chart

// packages/svelte/src/Chart.svelte
<script lang="ts">
  import { onMount, onDestroy, createEventDispatcher } from 'svelte'
  import type { Chart as ChartCore, ChartConfig, ChartData } from '@ldesign/chart-core'
  import { createChart } from '@ldesign/chart-core'

  export let type: ChartConfig['type']
  export let data: ChartData
  export let title: string | undefined = undefined
  export let theme: string | undefined = undefined
  export let darkMode: boolean | undefined = undefined
  export let responsive: boolean | undefined = undefined
  export let config: Partial<ChartConfig> | undefined = undefined

  const dispatch = createEventDispatcher<{
    init: ChartCore
    click: any
  }>()

  let container: HTMLElement
  let chart: ChartCore | undefined

  onMount(() => {
    if (container) {
      const chartConfig: ChartConfig = {
        type,
        data,
        title,
        theme,
        darkMode,
        responsive,
        ...config,
      }

      chart = createChart(container, chartConfig)

      chart.on('click', (params: any) => {
        dispatch('click', params)
      })

      dispatch('init', chart)
    }
  })

  onDestroy(() => {
    chart?.dispose()
  })

  export function getChart(): ChartCore | undefined {
    return chart
  }

  export function resize(): void {
    chart?.resize()
  }

  $: if (chart && data) {
    chart.updateData(data)
  }

  $: if (chart && theme) {
    chart.setTheme(theme)
  }

  $: if (chart && darkMode !== undefined) {
    chart.setDarkMode(darkMode)
  }
</script>

<div bind:this={container} style="width: 100%; height: 100%;"></div>
