// packages/react/src/components/LChart.tsx
import React, { useMemo, CSSProperties } from 'react'
import { useChart, type ChartOption } from '../hooks/useChart'

/**
 * LChart 组件的 Props
 */
export interface LChartProps {
  /**
   * 图表配置选项
   */
  option: ChartOption

  /**
   * 主题名称
   * @default 'default'
   */
  theme?: string

  /**
   * 容器宽度
   * @default '100%'
   */
  width?: number | string

  /**
   * 容器高度
   * @default '400px'
   */
  height?: number | string

  /**
   * 是否自动调整大小
   * @default true
   */
  autoResize?: boolean

  /**
   * 自定义类名
   */
  className?: string

  /**
   * 自定义样式
   */
  style?: CSSProperties
}

/**
 * LChart 组件的 Ref
 */
export interface LChartRef {
  /**
   * 图表实例
   */
  chartInstance: any | null

  /**
   * 手动调整图表大小
   */
  resize: () => void

  /**
   * 销毁图表实例
   */
  dispose: () => void
}

/**
 * LChart - React chart component
 * 
 * @example
 * ```tsx
 * function App() {
 *   const option = {
 *     series: [{ type: 'line', data: [1, 2, 3, 4, 5] }]
 *   }
 *   
 *   return <LChart option={option} theme="default" />
 * }
 * ```
 */
export const LChart = React.forwardRef<LChartRef, LChartProps>((props, ref) => {
  const {
    option,
    theme = 'default',
    width = '100%',
    height = '400px',
    autoResize = true,
    className,
    style
  } = props

  const { containerRef, chartInstance, resize, dispose } = useChart({
    option,
    theme,
    autoResize
  })

  // 暴露方法给父组件
  React.useImperativeHandle(ref, () => ({
    chartInstance,
    resize,
    dispose
  }), [chartInstance, resize, dispose])

  // 容器样式
  const containerStyle = useMemo<CSSProperties>(() => {
    const normalizedWidth = typeof width === 'number' ? `${width}px` : width
    const normalizedHeight = typeof height === 'number' ? `${height}px` : height

    return {
      width: normalizedWidth,
      height: normalizedHeight,
      ...style
    }
  }, [width, height, style])

  return (
    <div
      ref={containerRef}
      className={className ? `l-chart ${className}` : 'l-chart'}
      style={containerStyle}
    />
  )
})

LChart.displayName = 'LChart'

// packages/vue/src/components/LChart.vue
<template>
  <div 
    ref="containerRef" 
    class="l-chart"
    :style="containerStyle"
  />
</template>

<script setup lang="ts">
import { computed, toRef } from 'vue'
import { useChart, type ChartOption } from '../composables/useChart'

/**
 * LChart 组件属性
 */
export interface LChartProps {
  /** 图表配置 */
  option: ChartOption
  /** 主题名称或主题对象 */
  theme?: string
  /** 宽度 */
  width?: number | string
  /** 高度 */
  height?: number | string
  /** 自动调整大小 */
  autoResize?: boolean
}

const props = withDefaults(defineProps<LChartProps>(), {
  theme: 'default',
  width: '100%',
  height: '400px',
  autoResize: true
})

/**
 * 容器样式
 */
const containerStyle = computed(() => ({
  width: typeof props.width === 'number' ? `${props.width}px` : props.width,
  height: typeof props.height === 'number' ? `${props.height}px` : props.height
}))

/**
 * 使用 useChart composable
 */
const { containerRef, chartInstance, resize, dispose } = useChart({
  option: toRef(props, 'option'),
  theme: toRef(props, 'theme'),
  autoResize: props.autoResize
})

/**
 * 暴露方法给父组件
 */
defineExpose({
  chartInstance,
  resize,
  dispose
})
</script>

<style scoped>
.l-chart {
  position: relative;
  overflow: hidden;
}
</style>
