// packages/svelte/src/Chart.svelte
<script lang="ts">
  import { onMount, onDestroy, createEventDispatcher } from 'svelte'
  import type { Chart as ChartCore, ChartConfig, ChartData } from '@ldesign/chart-core'
  import { createChart } from '@ldesign/chart-core'

  export let type: ChartConfig['type']
  export let data: ChartData
  export let title: string | undefined = undefined
  export let theme: string | undefined = undefined
  export let darkMode: boolean | undefined = undefined
  export let responsive: boolean | undefined = undefined
  export let config: Partial<ChartConfig> | undefined = undefined

  const dispatch = createEventDispatcher<{
    init: ChartCore
    click: any
  }>()

  let container: HTMLElement
  let chart: ChartCore | undefined

  onMount(() => {
    if (container) {
      const chartConfig: ChartConfig = {
        type,
        data,
        title,
        theme,
        darkMode,
        responsive,
        ...config,
      }

      chart = createChart(container, chartConfig)

      chart.on('click', (params: any) => {
        dispatch('click', params)
      })

      dispatch('init', chart)
    }
  })

  onDestroy(() => {
    chart?.dispose()
  })

  export function getChart(): ChartCore | undefined {
    return chart
  }

  export function resize(): void {
    chart?.resize()
  }

  $: if (chart && data) {
    chart.updateData(data)
  }

  $: if (chart && theme) {
    chart.setTheme(theme)
  }

  $: if (chart && darkMode !== undefined) {
    chart.setDarkMode(darkMode)
  }
</script>

<div bind:this={container} style="width: 100%; height: 100%;"></div>

// packages/angular/src/components/chart.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  OnInit,
  OnChanges,
  OnDestroy,
  ElementRef,
  ViewChild,
  SimpleChanges,
  ChangeDetectionStrategy,
} from '@angular/core'
import type { Chart as ChartCore, ChartConfig, ChartData } from '@ldesign/chart-core'
import { createChart } from '@ldesign/chart-core'

@Component({
  selector: 'ldesign-chart',
  template: '<div #chartContainer style="width: 100%; height: 100%;"></div>',
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
})
export class ChartComponent implements OnInit, OnChanges, OnDestroy {
  @ViewChild('chartContainer', { static: true }) chartContainer!: ElementRef<HTMLElement>

  @Input() type!: ChartConfig['type']
  @Input() data!: ChartData
  @Input() title?: string
  @Input() theme?: string
  @Input() darkMode?: boolean
  @Input() responsive?: boolean
  @Input() config?: Partial<ChartConfig>

  @Output() chartInit = new EventEmitter<ChartCore>()
  @Output() chartClick = new EventEmitter<any>()

  private chart?: ChartCore

  ngOnInit(): void {
    this.initChart()
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (this.chart) {
      if (changes['data'] && !changes['data'].firstChange) {
        this.chart.updateData(changes['data'].currentValue)
      }
      if (changes['theme'] && !changes['theme'].firstChange) {
        this.chart.setTheme(changes['theme'].currentValue)
      }
      if (changes['darkMode'] && !changes['darkMode'].firstChange) {
        this.chart.setDarkMode(changes['darkMode'].currentValue)
      }
    }
  }

  ngOnDestroy(): void {
    this.chart?.dispose()
  }

  private initChart(): void {
    if (!this.chartContainer?.nativeElement)
      return

    const chartConfig: ChartConfig = {
      type: this.type,
      data: this.data,
      title: this.title,
      theme: this.theme,
      darkMode: this.darkMode,
      responsive: this.responsive,
      ...this.config,
    }

    this.chart = createChart(this.chartContainer.nativeElement, chartConfig)

    this.chart.on('click', (params: any) => {
      this.chartClick.emit(params)
    })

    this.chartInit.emit(this.chart)
  }

  getChart(): ChartCore | undefined {
    return this.chart
  }

  resize(): void {
    this.chart?.resize()
  }
}
